### PR TITLE
Prevent NullReferenceException when RawResponseBody is Null inside ServiceException

### PR DESCRIPTION
**Pull request by Danny4021**
Fixes [#2303](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2303)

### Changes proposed in this pull request
- Fix possible NullReferenceException in method `IsMatch` when no RawResponseBody is provided
- Add UnitTest for described case

### Other links
- See Issue [#2303](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2303)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/799)

### CODE REVIEW

**Review by andrueastman — COMMENTED** [review]
Thanks for the contribution here @Danny4021 

Any chance you can bump the version [here ](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/797c7308c95a9b8b02de24733096c764a82a4ee0/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L24) to 3.1.7 as well as add a note [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/797c7308c95a9b8b02de24733096c764a82a4ee0/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L27) before we merge

**Comment by Danny4021** [comment]
Hello @andrueastman 
I've added the requested changes.
I'll just have to talk to my employer about the Contributor License Agreement before agreeing to it.
I'll agree to it once I have the necessary permissions from my employer.

**Comment by andrueastman** [comment]
@Danny4021 Any chance you have feedback on this?

**Comment by Danny4021** [comment]
Hello @andrueastman,
I'm sorry for the delay but my employer has been busy this past week and couldn't give me an answer yet.
I'll be able to get back to you next week, if that's alright with you.

**Comment by andrueastman** [comment]
No worries @Danny4021. I was just checking if this is still going through.

**Comment by Danny4021** [comment]
Hello @andrueastman 
my employer agreed to the license agreement. Do I have to merge the develop again or change the version before merging?

**Comment by Danny4021** [comment]
@microsoft-github-policy-service agree company="Evy Solutions GmbH"

**Comment by Danny4021** [comment]
@andrueastman  I resolved the merge conflict and bumped the version up to 3.1.8
If that wasn't correct I'll revert the change

**Review by andrueastman — APPROVED** [review]
Thanks for the contribution

**Pull request merged**
