### PR TITLE
Proper Batching support

### LINKED ISSUE #612: Evaluate improving batching support
Evaluate improving batching support based on the work @svrooij did [here](https://github.com/svrooij/msgraph-sdk-dotnet-batching/).

We could integrate this in the .NET core library and also evaluate a similar approach for all other languages we support.

By the way, incredible work @svrooij. Kudos!

### PR DESCRIPTION
**Pull request by svrooij**
Fixes #612 

### Changes proposed in this pull request
- Automatically splitting batch requests into multiple batches without the user having to manage it.

### Other links
- https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/29
- https://github.com/svrooij/msgraph-sdk-dotnet-batching/ (same code, but implemented as extension)
- https://svrooij.io/2023/03/03/batching-in-microsoft-graph/#adding-users-with-batching-exception (describing issue)

As [promised](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/612#issuecomment-1453872641) to @maisarissi a PR with my extension code integrated in the Graph SDK for dotnet.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/613)

### CODE REVIEW

**Review by andrueastman — COMMENTED** [review]
Thanks for the contribution @svrooij

Just a couple of suggestions from my side

**Comment by svrooij** [comment]
@andrueastman Great suggestions.

Code maid helped me cleanup the code a bit. And converted the IEnumerable to a HashSet

**Review by andrueastman — APPROVED** [review]
Thanks again for taking the time to make the contribution @svrooij

**Comment by svrooij** [comment]
As a new contributor can you please explain how the release will go @andrueastman ?
Is it automatically, or do you have a certain release cycle?

**Comment by andrueastman** [comment]
We should see the release deployed after #614 is merged.

**Pull request merged**
